version: '3.8'

services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"  # Expone el puerto 8080 de la app al puerto 8080 del host
    depends_on:
      - mailhog  # Asegura que MailHog esté listo antes de iniciar la aplicación

  mailhog:
    image: mailhog/mailhog  # Usa la imagen oficial de MailHog
    container_name: mailhog
    ports:
      - "8025:8025"   # Interfaz web accesible en localhost:8025
      - "1025:1025"   # Puerto SMTP accesible para la app en localhost:1025
